name: gridview_teste
description: Aplicativo de curso de violão com área administrativa e área do aluno.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.4
  shared_preferences: ^2.2.2
  video_player: ^2.8.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  cached_network_image: ^3.3.0
  youtube_player_iframe: ^4.0.4
  youtube_player_flutter: ^9.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/thumbCurso.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/thumbCurso.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_screen.png
    - assets/images/thumbCurso.png
    - assets/images/fundo_login.png
    - assets/images/fundo_clavedesol.png